services:
  - type: web
    name: callallocation-backend
    runtime: node
    repo: https://github.com/Hxrpinder529/callallocation-backend.git
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ZEPTOMAIL_PASSWORD
        sync: false

  - type: worker
    name: callallocation-keepalive
    runtime: node
    repo: https://github.com/Hxrpinder529/callallocation-backend.git
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node keepalive.js
    envVars:
      - key: RENDER_URL
        value: https://callallocation-backend.onrender.com